server:
  port: 9696
spring:
  application:
    name: consumer-jt1

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jt:123456@localhost:9898/eureka
logging:
  level:
    root: INFO
